<?php

/* ------------------------------------------------------------------------
   Commissioner Tools Parent Menu
------------------------------------------------------------------------ */
function fod_register_commissioner_tools_menu() {
    add_menu_page(
        'Commissioner Tools',
        'Commish Tools',
        'manage_options',
        'commissioner-tools',
        'fod_render_commish_tools_dashboard',
        'dashicons-shield',
        58
    );

    add_submenu_page(
        'commissioner-tools',
        'Arbitration Approvals',
        'Arbitration Approvals',
        'read', // Capability (checked inside the function for commissioner status)
        'fod-arb-approvals',
        'fod_render_arb_approval_page'
    );
}
add_action('admin_menu', 'fod_register_commissioner_tools_menu');

/**
 * Simple dashboard/overview for Commish Tools
 */
function fod_render_commish_tools_dashboard() {
    ?>
    <div class="wrap">
        <h1>League Commissioner Tools</h1>
        <p>Welcome to the central hub for league operations. Use the sidebar menu or the links below to access specific tools.</p>
        
        <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin-top: 20px;">
            <div class="card" style="padding: 20px;">
                <h3>Arbitration Approvals</h3>
                <p>Review and process manager arbitration and extension decisions.</p>
                <a href="<?php echo admin_url('admin.php?page=fod-arb-approvals'); ?>" class="button button-primary">Open Approvals</a>
            </div>
            
            <div class="card" style="padding: 20px;">
                <h3>Assign Player</h3>
                <p>Manually assign a player to a team and set their initial contract years.</p>
                <a href="<?php echo admin_url('admin.php?page=fod-assign-player'); ?>" class="button button-primary">Open Assignment Tool</a>
            </div>

            <div class="card" style="padding: 20px;">
                <h3>Import Players</h3>
                <p>Bulk upload players from CSV files generated by the Python pipeline.</p>
                <a href="<?php echo admin_url('admin.php?page=fod-player-importer'); ?>" class="button button-primary">Open Importer</a>
            </div>
        </div>

        <!-- NEW: Recent Pending Transactions -->
        <div class="card" style="margin-top: 20px; padding: 20px; max-width: 100%;">
            <h3>Recent Pending Fantrax Transactions</h3>
            <p>The following transactions have not yet been marked as "Processed" on the Fantrax website.</p>
            <?php
            $pending_query = new WP_Query([
                'post_type' => 'transaction',
                'posts_per_page' => 10,
                'meta_query' => [
                    'relation' => 'AND',
                    [
                        'relation' => 'OR',
                        ['key' => 'fantrax_processed', 'value' => '0'],
                        ['key' => 'fantrax_processed', 'compare' => 'NOT EXISTS']
                    ],
                    [
                        'key'     => 'transaction_type',
                        'value'   => ['Trade', 'Free Agent Signing', 'Waiver Claim', 'Draft Pick', 'Team Option'],
                        'compare' => 'IN'
                    ]
                ]
            ]);

            if ($pending_query->have_posts()) : ?>
                <table class="wp-list-table widefat fixed striped">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>League</th>
                            <th>Transaction Summary</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php while ($pending_query->have_posts()) : $pending_query->the_post(); 
                            $tid = get_the_ID();
                            $toggle_url = wp_nonce_url(admin_url('admin-post.php?action=toggle_fantrax_processed&post_id=' . $tid), 'toggle_fantrax_' . $tid);
                        ?>
                            <tr>
                                <td><?php echo get_the_date('M j, g:i a'); ?></td>
                                <td><?php echo esc_html(get_post_meta($tid, 'league_id', true)); ?></td>
                                <td><?php the_title(); ?></td>
                                <td>
                                    <a href="<?php echo esc_url($toggle_url); ?>" class="button button-small">Mark Processed</a>
                                </td>
                            </tr>
                        <?php endwhile; ?>
                    </tbody>
                </table>
                <p><a href="<?php echo admin_url('edit.php?post_type=transaction'); ?>">View All Transactions &rarr;</a></p>
            <?php else : ?>
                <p style="color: green; font-weight: bold;">✅ All transactions have been processed on Fantrax!</p>
            <?php endif; wp_reset_postdata(); ?>
        </div>
    </div>
    <?php
}
