<?php

/* ------------------------------------------------------------------------
   Commissioner Tools Parent Menu
------------------------------------------------------------------------ */
function fod_register_commissioner_tools_menu() {
    add_menu_page(
        'Commissioner Tools',
        'Commish Tools',
        'manage_options',
        'commissioner-tools',
        'fod_render_commish_tools_dashboard',
        'dashicons-shield',
        58
    );

    add_submenu_page(
        'commissioner-tools',
        'Arbitration Approvals',
        'Arbitration Approvals',
        'read', // Capability (checked inside the function for commissioner status)
        'fod-arb-approvals',
        'fod_render_arb_approval_page'
    );

    add_submenu_page(
        'commissioner-tools',
        'Account Approvals',
        'Account Approvals',
        'manage_options',
        'fod-account-approvals',
        'fod_render_account_approval_page'
    );
}
add_action('admin_menu', 'fod_register_commissioner_tools_menu');

/**
 * Simple dashboard/overview for Commish Tools
 */
function fod_render_commish_tools_dashboard() {
    ?>
    <div class="wrap">
        <h1>League Commissioner Tools</h1>
        <p>Welcome to the central hub for league operations. Use the sidebar menu or the links below to access specific tools.</p>
        
        <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin-top: 20px;">
            <div class="card" style="padding: 20px;">
                <h3>Arbitration Approvals</h3>
                <p>Review and process manager arbitration and extension decisions.</p>
                <a href="<?php echo admin_url('admin.php?page=fod-arb-approvals'); ?>" class="button button-primary">Open Approvals</a>
            </div>
            
            <div class="card" style="padding: 20px;">
                <h3>Assign Player</h3>
                <p>Manually assign a player to a team and set their initial contract years.</p>
                <a href="<?php echo admin_url('admin.php?page=fod-assign-player'); ?>" class="button button-primary">Open Assignment Tool</a>
            </div>

            <div class="card" style="padding: 20px;">
                <h3>Import Players</h3>
                <p>Bulk upload players from CSV files generated by the Python pipeline.</p>
                <a href="<?php echo admin_url('admin.php?page=fod-player-importer'); ?>" class="button button-primary">Open Importer</a>
            </div>
        </div>

        <!-- NEW: Recent Pending Transactions -->
        <div class="card" style="margin-top: 20px; padding: 20px; max-width: 100%;">
            <h3>Recent Pending Fantrax Transactions</h3>
            <p>The following transactions have not yet been marked as "Processed" on the Fantrax website.</p>
            <?php
            $pending_query = new WP_Query([
                'post_type' => 'transaction',
                'posts_per_page' => 10,
                'meta_query' => [
                    'relation' => 'AND',
                    [
                        'relation' => 'OR',
                        ['key' => 'fantrax_processed', 'value' => '0'],
                        ['key' => 'fantrax_processed', 'compare' => 'NOT EXISTS']
                    ],
                    [
                        'key'     => 'transaction_type',
                        'value'   => ['Trade', 'Free Agent Signing', 'Waiver Claim', 'Draft Pick', 'Team Option'],
                        'compare' => 'IN'
                    ]
                ]
            ]);

            if ($pending_query->have_posts()) : ?>
                <table class="wp-list-table widefat fixed striped">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>League</th>
                            <th>Transaction Summary</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php while ($pending_query->have_posts()) : $pending_query->the_post(); 
                            $tid = get_the_ID();
                            $toggle_url = wp_nonce_url(admin_url('admin-post.php?action=toggle_fantrax_processed&post_id=' . $tid), 'toggle_fantrax_' . $tid);
                        ?>
                            <tr>
                                <td><?php echo get_the_date('M j, g:i a'); ?></td>
                                <td><?php echo esc_html(get_post_meta($tid, 'league_id', true)); ?></td>
                                <td><?php the_title(); ?></td>
                                <td>
                                    <a href="<?php echo esc_url($toggle_url); ?>" class="button button-small">Mark Processed</a>
                                </td>
                            </tr>
                        <?php endwhile; ?>
                    </tbody>
                </table>
                <p><a href="<?php echo admin_url('edit.php?post_type=transaction'); ?>">View All Transactions &rarr;</a></p>
            <?php else : ?>
                <p style="color: green; font-weight: bold;">✅ All transactions have been processed on Fantrax!</p>
            <?php endif; wp_reset_postdata(); ?>
        </div>
    </div>
    <?php
}

/* ------------------------------------------------------------------------
   Player Data List: Add FOD ID Column
------------------------------------------------------------------------ */
function fod_set_player_columns($columns) {
    $new_columns = [];
    foreach($columns as $key => $value) {
        if ($key === 'title') {
            $new_columns['fod_id'] = 'FOD ID';
        }
        $new_columns[$key] = $value;
    }
    return $new_columns;
}
add_filter('manage_playerdata_posts_columns', 'fod_set_player_columns');
add_filter('manage_nbaplayer_posts_columns', 'fod_set_player_columns');

function fod_populate_player_columns($column, $post_id) {
    if ($column === 'fod_id') {
        $fod_id = get_post_meta($post_id, 'fod_id', true);
        echo '<strong>' . esc_html($fod_id ?: '–') . '</strong>';
    }
}
add_action('manage_playerdata_posts_custom_column', 'fod_populate_player_columns', 10, 2);
add_action('manage_nbaplayer_posts_custom_column', 'fod_populate_player_columns', 10, 2);

/* ------------------------------------------------------------------------
   Edit Player Screen: FOD ID Meta Box
------------------------------------------------------------------------ */
function fod_add_player_id_metabox() {
    $screens = ['playerdata', 'nbaplayer'];
    foreach ($screens as $screen) {
        add_meta_box(
            'fod_player_id_box',
            'Internal Unique ID',
            'fod_render_player_id_metabox',
            $screen,
            'side',
            'high'
        );
    }
}
add_action('add_meta_boxes', 'fod_add_player_id_metabox');

function fod_render_player_id_metabox($post) {
    $fod_id = get_post_meta($post->ID, 'fod_id', true);
    echo '<p style="font-size: 1.2em; font-weight: bold; color: #0073aa; margin: 0;">' . esc_html($fod_id ?: 'Not Generated Yet') . '</p>';
    echo '<p class="description">This ID is unique to this specific player record and is used for reliable CSV importing.</p>';
}

/**
 * Display FOD ID prominently below the player name/title
 */
function fod_display_id_below_title() {
    global $post;
    if ( !is_object($post) || !in_array($post->post_type, ['playerdata', 'nbaplayer']) ) return;

    $fod_id = get_post_meta($post->ID, 'fod_id', true);
    if ( $fod_id ) {
        echo '<div class="notice notice-info" style="margin: 10px 0; padding: 10px; border-left: 4px solid #0073aa; background: #fff; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">';
        echo '<span style="font-weight: bold; color: #0073aa; text-transform: uppercase; font-size: 0.85em; display: block; margin-bottom: 2px;">Internal Unique ID</span>';
        echo '<code style="font-size: 1.4em; font-weight: bold; background: none; border: none; padding: 0;">' . esc_html($fod_id) . '</code>';
        echo '</div>';
    }
}
add_action('edit_form_after_title', 'fod_display_id_below_title');
