name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare Theme Folder
        run: |
          mkdir deploy_folder
          cp -r functions.php style.css inc JS acf-json deploy_folder/

      - name: Sync to Production Server
        run: |
          sudo apt-get install -y lftp
          lftp -c "set sftp:auto-confirm yes; open -u ${{ secrets.PROD_SFTP_USERNAME }},${{ secrets.PROD_SFTP_PASSWORD }} sftp://sftp.wp.com:22; mirror -R ./deploy_folder/ htdocs/wp-content/themes/twentytwentytwo-child/"