name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare Theme Folder
        run: |
          mkdir deploy_folder
          cp -r functions.php style.css inc JS acf-json deploy_folder/

      - name: Sync to Production Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ''
          ARGS: "-rlgoDzvc -i"
          SOURCE: "deploy_folder/"
          REMOTE_HOST: "sftp.wp.com"
          REMOTE_USER: ${{ secrets.PROD_SFTP_USERNAME }}
          REMOTE_PASSWORD: ${{ secrets.PROD_SFTP_PASSWORD }}
          REMOTE_PORT: 22
          TARGET: "htdocs/wp-content/themes/twentytwentytwo-child/"
          EXCLUDE: "/.git/, /.github/"